name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: kivy/buildozer-action@v1
        with:
          command: buildozer android debug
